skillMetadata:
  sections:
    - name: Skill Data Sources
      fields:
        - name: datetime_skill
          type: text
          label: Date and Time
          value: skill-date-time.mycroftai
        - name: examples_skill
          type: text
          label: Examples
          value: ovos-skills-info.openvoiceos
    - name: Personalization
      fields:
        - name: wallpaper
          type: text
          label: Wallpaper
          value: default.jpg
        - name: persistent_menu_hint
          type: bool
          label: Permanent Pull-Down Menu Hint
          value: false
    - name: Examples
      fields:
        - name: examples_enabled
          type: bool
          label: Enable Examples
          value: true
        - name: randomize_examples
          type: bool
          label: Randomize Example Entries
          value: true
        - name: examples_prefix
          type: bool
          label: Prefix examples with 'Ask Me'
          value: true
